### ISSUE TITLE
Enforce unidirectional workflow

### ISSUE THREAD

**Issue by cmbz** [opendp/dp-wizard#89] opened 2024-10-23 21:15 UTC
## Overview
- This functionality ensures that users cannot reverse course in the workflow. The workflow always proceeds from `Select Dataset` to `Define Analysis` and concludes with `Download Results`

## Issues
- [ ] https://github.com/opendp/dp-creator-ii/issues/32

## Dependencies
- None

## Related
- https://github.com/opendp/dp-creator-ii/issues/86

**Comment by mccalluc** [comment] 2024-12-18 02:28
Duplicate of #32, which might fit into a different category.

**Closed by mccalluc** 2024-12-18 02:28 UTC
Labels: group, 8 weeks?
